platform :ios, '5.1'

pod 'CocoaLumberjack'
pod 'UIColor-Utilities'
pod 'UIImage-Categories'
pod 'MBProgressHUD'
pod 'JSONKit'
pod 'ASIHTTPRequest'
pod 'CommonCrypto'
pod 'iCarousel'
pod 'SDWebImage'

